name: verify_multi

on:
  workflow_dispatch:

jobs:
  cross-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: linux/arm64
          - arch: linux/arm
          - arch: linux/s390x
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Clean Table
        run:
          docker stop $(docker ps -aq) && yes | docker system prune -a
      -
        name: QEMU
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      -
        name: Create Proxy
        shell: bash
        run: |
          curl -fsSL bit.ly/warp_socks | sh -s -- "warp_socks" ${{ matrix.arch }} "1" "9091"
          date && sleep 60 && docker ps -a && date && docker logs warp_socks

      - name: Check proxy status
        id: check
        run: |
          set +e
          trace=$(curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=on")
          echo ::set-output name=trace::$trace
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"